### PR TITLE
Merge Development to Main to close Issues

### LINKED ISSUE #6: Writing PDFs to the designated dir breaks if current dir changes
Solution: pass the absolute path instead.

### LINKED ISSUE #9: Prototype check boxes to track coordinates
Use the checkbox form object to track the location of a checkbox within the generated PDF document.

### LINKED ISSUE #30: Generate flat file PDFs from an EDF
### Discussed in https://github.com/TrustTheVote-Project/BallotLab/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **stratofax** July 21, 2022</sup>
Using data from an approved EDF, generate ballots styled according to EAC standards using the data from the EDF. These ballots will not include any form elements (like checkboxes or radio buttons) but are intended for layout review.</div>

Use the `ballotmaker make` sub-command to execute this  code.

### LINKED ISSUE #64: Generate ballot PDFs with embedded form objects
Use the form objects to:

- Associate unique EDF IDs with each candidate, ballot question, etc.
- Identify the exact coodinates of the "checkbox oval" by reading the location of the form object using any third party PDF utility -- or Markit, to place ballot markings based on how a Markit user casts their votes.

The form objects will ultimately be obscured on the PDF by a "regulation sized" OCR marking oval, either empty (white), or filled (black) when votes are cast and marked, so they will look exactly like a "flat file" PDF ballot with no form objects.

## Notes

From J. Sebes:

- The write in fields are obviously text form field objects, but the "bubbles" Cliff will have to say what type of beast they are.
- For whatever empty oval shape you are laying down, we will need a JPEG of the same shape, solid black; that's what will get pasted in the coordinates for each voter selection in the app.
- You can have labelled objects for each bubble, such that for each selection that the user does _not_ choose, it will end up printing out looking like an empty bubble.

### LINKED ISSUE #110: Generate flat file ballots from all four precincts
Use the new [september_test_case.json at main · TrustTheVote-Project/NIST-1500-100-103-examples](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/september_test_case.json) to generate all four (4) ballots.

### PR DESCRIPTION
**Pull request by stratofax**
This version (0.1.3) of BallotMaker generates ballots with hidden widgets, thus completing the work for [Milestone 2. Generate ballot PDFs with embedded form objects](https://github.com/TrustTheVote-Project/BallotLab/milestone/2). This merge to main will close the associated issues and milestones.

Closes BallotLab [milestone #2](https://github.com/TrustTheVote-Project/BallotLab/milestone/2)

### CODE REVIEW

**Comment by ion-oset** [comment]
Checklist to finish before hitting merge.

- [x] Version updated in:
  - [x] `pyproject.toml`
  - [x] `CHANGELOG.md`
- [ ] ~Tag `development` branch as version (`v0.1.3`).~
- [x] Close all remaining milestone issues, or ~remove them from the milestone~ link them to this PR.

After the merge is successful and tests all pass

- [x] Tag `main` branch as version (`v0.1.3`).

_EDIT_: As discussed on the call: the tag should be on `main` _after_ the merge.

_Notes_:

- This should be a regular merge not a rebase merge.
- We should come up with standard message for closing milestones. Something like:

   ```
   Closes BallotLab milestone #2: https://github.com/TrustTheVote-Project/BallotLab/milestone/2
   ```
   - In this case it closes milestone #1 also, so it might be two lines.

**Comment by ion-oset** [comment]
Some how I missed the linked issues - yes that would address closing them!

I've unchecked `Tag development branch as version (v0.1.3)` though. I don't see any [tags on the upstream repository](https://github.com/TrustTheVote-Project/BallotLab/tags)

**Comment by stratofax** [comment]
The tags exist on my local copy of the repo on the development branch.

```
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|development✓
➤ git tag --list
v0.1.2
v0.1.3
```

**Comment by stratofax** [comment]
I think I should delete the `development` branch, having reached this milestone.  We can then create new branches for the next milestone. Thoughts?

**Comment by stratofax** [comment]
Tagged with lightweight tag `v0.1.3`: [Tags · TrustTheVote-Project/BallotLab](https://github.com/TrustTheVote-Project/BallotLab/tags)

**Comment by ion-oset** [comment]
> I think I should delete the development branch, having reached this milestone. We can then create new branches for the next milestone. Thoughts?

Move `development` to be on what is now `main`.

```
     git branch -f main development
```

The next milestone starts from there, and new branches are based on `development`, not on `main`.

The purpose of a development branch is as the place to combine all accepted branches that are part of a milestone. When they are stable and ready they merge into the stable branch (`main`).

**Comment by stratofax** [comment]
I agree with the premise of the development branch, I'm proposing one option to implement this -- instead of having a long running `development` branch, create branches for each milestone, merge them onto `main` when the milestone is completed, delete the milestone branch, rinse, repeat.

You're proposing another option -- maintain the `development` branch as a persistent target for work around a specific milestone. When we complete a milestone, use the `git branch --force` command to ensure that the `development` branch is at exactly the same point as `main`.

Note: I checked the git documentation and it seems like the way to do what you describe, 

> Move `development` to be on what is now `main`

would look like this:

```
     git branch -f development main 
```

where the branchname is `development` and the start-point is `main`

Here's the git documentation command template:

```
git branch [-f] <branchname> [<start-point>]
```

So, this post is my attempt to make sure I understand your implementation strategy, as well as mine. 

Both strategies share essential features:

* there's a primary development branch where all the work for a milestone lands before it's merged to `main`
* When we reach a milestone and merge to main we ensure that the development branch and main are identical.

The difference is (as far as I can tell) exactly **how** we ensure that `main` and the milestone development branch are identical immedately after merging. You suggest using a git command on a long-lived development branch; I suggest creating a new branch off of main for the upcoming milestone.

Let's discuss this at today's meeting.

**Comment by ion-oset** [comment]
> Note: I checked the git documentation and it seems like the way to do what you describe,
>
> > Move development to be on what is now main
>
> would look like this:
>
>     git branch -f development main 
>
> where the branch name is `development` and the start-point is `main`

You are correct. I want to note that I typed that wrong _even after I looked it up_ and noted that it was the way it was. It's the reverse of nearly every other branch option, where the target branch name comes at the end. Git is is many things but consistent is not one of them.

**Comment by ion-oset** [comment]
> So, this post is my attempt to make sure I understand your implementation strategy, as well as mine.




Both strategies share essential features:

    there's a primary development branch where all the work for a milestone lands before it's merged to main
    When we reach a milestone and merge to main we ensure that the development branch and main are identical.

The difference is (as far as I can tell) exactly how we ensure that main and the milestone development branch are identical immedately after merging. You suggest using a git command on a long-lived development branch; I suggest creating a new branch off of main for the upcoming milestone.

**Comment by ion-oset** [comment]
> So, this post is my attempt to make sure I understand your implementation strategy, as well as mine.

I've moved this to the [branching and merging strategy discussion](https://github.com/ion-oset/developer-commons/discussions/27?sort=new#discussioncomment-3745458) so whatever we decide doesn't get lost on a closed PR thread.

**Pull request merged**
